services:
  postgres:
    image: postgres:16-alpine
    container_name: sob-alimentaria-db
    restart: always
    environment:
      - POSTGRES_USER=admin_negocio
      - POSTGRES_PASSWORD=clave_segura_123
      - POSTGRES_DB=comidas_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    networks:
      - sob_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_negocio"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sob-alimentaria-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy      
    environment:
      - DEBUG=${DEBUG:-false}
      - DATABASE_URL=postgresql://admin_negocio:clave_segura_123@postgres:5432/sob_db?schema=public
      - NEXTAUTH_URL=http://localhost:3000
    command: >
      sh -c "
        npx prisma migrate deploy &&
        if [ \"$$DEBUG\" = \"true\" ]; then
          echo '=== MODO DEBUG DETECTADO: Ejecutando seed... ===' &&
          npx prisma db seed;
        fi &&
        npm run start:prod
      "git
    ports:
      - "3000:3000"
    volumes:
      - ./db:/app/db
    networks:
      - sob_net

networks:
  sob_net:
    driver: bridge

volumes:
  postgres_data:


## NOTAS  de implementaciones anteriores

  # image: postgres:16-alpine
    # container_name: sob-alimentaria-db
    # restart: unless-stopped
    # environment:
    #   POSTGRES_USER: sob_user
    #   POSTGRES_PASSWORD: sob_password
    #   POSTGRES_DB: sob_db
    # ports:
    #   - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - sob_net
    
  # caddy:
  #   image: caddy:2-alpine
  #   container_name: sob-alimentaria-caddy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile:ro
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   depends_on:
  #     - app
  #   networks:
  #     - sob_net

# volumes:
#   sob_db:
  # caddy_data:
  # caddy_config:
